[[GibbsSeaWater]]
arch = "aarch64"
git-tree-sha1 = "d3d71a86465d8144b78a74305758927e69eaf4b1"
os = "macos"

    [[GibbsSeaWater.download]]
    sha256 = "c94e9dec8f594c2796ce973f34f4cace3a703428e2405022115e75be341480cd"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.aarch64-apple-darwin.tar.gz"
[[GibbsSeaWater]]
arch = "aarch64"
git-tree-sha1 = "806bbdb81a1fb9b7e5b88aaebdac1fc5852412a0"
libc = "glibc"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "734c39ce479f57e3aec9168e5485f945b88523152156e89022615b47ad547e29"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.aarch64-linux-gnu.tar.gz"
[[GibbsSeaWater]]
arch = "aarch64"
git-tree-sha1 = "b3d9313943b90aba598f2bb6cec97e2810bc1d03"
libc = "musl"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "8df597bafadc8c260c01e50acb2740306ac4582d916b9b9c1bec36a5e537d59f"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.aarch64-linux-musl.tar.gz"
[[GibbsSeaWater]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6b5a7498fa9f80d238a7b12809c18c64431aa26"
libc = "glibc"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "486160726a7cff282304a37cba104e0bd23b0ee33edddf874de7976ce81f6d55"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.armv6l-linux-gnueabihf.tar.gz"
[[GibbsSeaWater]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "512d8d05f474828869910aab061a7d7daad56f81"
libc = "musl"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "625d50e44de48dfa51913f25a46240fff4d3455eb24f47232ae6d88889618cc9"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.armv6l-linux-musleabihf.tar.gz"
[[GibbsSeaWater]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e3a50cdf94342c2c45705bba3bb98316519e488"
libc = "glibc"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "09379fec89d02e4a46bffd74497fd5ee6ef8bb62c8b11dbdac6ea818a0009304"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.armv7l-linux-gnueabihf.tar.gz"
[[GibbsSeaWater]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "850f5157e63ccd04f806fa3b7685a2cc3df16308"
libc = "musl"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "3112d5c276d86de4166b2e5fdb88ad11c97cfb604c1b352a1e5f55eae827eda5"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.armv7l-linux-musleabihf.tar.gz"
[[GibbsSeaWater]]
arch = "i686"
git-tree-sha1 = "71ff1a16beb226c7950c05ea20a3a2f8719c82a7"
libc = "glibc"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "14e65da1e22d89569f3d18c1a779d13fab2c19dffc3ee3b696ae44b9e4021012"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.i686-linux-gnu.tar.gz"
[[GibbsSeaWater]]
arch = "i686"
git-tree-sha1 = "0824f10861f7210ea20d2ffeab1a834514451cef"
libc = "musl"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "6930aa66783c75f01b8928b56ad0a0c25639469e3f27a628b6e6ab04d492bd01"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.i686-linux-musl.tar.gz"
[[GibbsSeaWater]]
arch = "i686"
git-tree-sha1 = "7e5e35f51467cd600130791010cb1d980e4e556a"
os = "windows"

    [[GibbsSeaWater.download]]
    sha256 = "4bea52e598c376aa8db2673f7b59433ed832f93fe3d79eb9cdd6099266d2b5eb"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.i686-w64-mingw32.tar.gz"
[[GibbsSeaWater]]
arch = "powerpc64le"
git-tree-sha1 = "49cd0bf7f77a35c27847cac2da5fc1a2971fa089"
libc = "glibc"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "2aac89e904430e573ed60951bac40e26b34c5a5ef3a3329bfe7533d3a3576361"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.powerpc64le-linux-gnu.tar.gz"
[[GibbsSeaWater]]
arch = "x86_64"
git-tree-sha1 = "fcb6e1f6e02299038ccc91d9d8edf9cc989f23aa"
os = "macos"

    [[GibbsSeaWater.download]]
    sha256 = "2809cd413d38f7ea150d84d9be029b4b41ae778a28de243af61902b55dedb706"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.x86_64-apple-darwin.tar.gz"
[[GibbsSeaWater]]
arch = "x86_64"
git-tree-sha1 = "e73ee9accf08cc3b4f99be3a249edcac27cdc080"
libc = "glibc"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "40d1ee1b0ab9b4886588066c8daad07c3889781c6e859018d7f21079fe2af7cc"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.x86_64-linux-gnu.tar.gz"
[[GibbsSeaWater]]
arch = "x86_64"
git-tree-sha1 = "e8c5b241dd044656f2d73e9388a9ab5d29e917ba"
libc = "musl"
os = "linux"

    [[GibbsSeaWater.download]]
    sha256 = "c64f7ace3b41dc0e56a96f86f92cc4290de664dcca69de3f42a4c63a38a7db8c"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.x86_64-linux-musl.tar.gz"
[[GibbsSeaWater]]
arch = "x86_64"
git-tree-sha1 = "31d48e11443e184d38ea6f439db83ca818f98d9f"
os = "freebsd"

    [[GibbsSeaWater.download]]
    sha256 = "f75ba8ac0aeec3626c865395f1fb59f5252bb260e0cbb466ad046fef81523e29"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.x86_64-unknown-freebsd.tar.gz"
[[GibbsSeaWater]]
arch = "x86_64"
git-tree-sha1 = "e5f86f0235819d0e5e88be7404720cf80bfd6edb"
os = "windows"

    [[GibbsSeaWater.download]]
    sha256 = "ef92c60c5727fe4f22f24c87955b6d2d4095bb829f0c5ed79e3c2f3b30a7ee91"
    url = "https://github.com/JuliaBinaryWrappers/GibbsSeaWater_jll.jl/releases/download/GibbsSeaWater-v3.5.1+0/GibbsSeaWater.v3.5.1.x86_64-w64-mingw32.tar.gz"
