# Autogenerated wrapper script for GibbsSeaWater_jll for i686-w64-mingw32
export libgswteos

JLLWrappers.@generate_wrapper_header("GibbsSeaWater")
JLLWrappers.@declare_library_product(libgswteos, "libgswteos.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgswteos,
        "bin\\libgswteos.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
